app/models.py
from app import db, login_manager
from flask_login import UserMixin
from werkzeug.security import generate_password_hash

class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    first_name = db.Column(db.String, nullable=False)
    last_name = db.Column(db.String, nullable=False)
    email = db.Column(db.String, nullable=False)
    password = db.Column(db.String)
    poke = db.relationship('Poke', backref='author', lazy='dynamic')

    # hashes our password when user signs up
    def hash_password(self, signup_password):
        return generate_password_hash(signup_password)
    
    # This method will assign our columns with their respective values
    def from_dict(self, user_data):
        self.first_name = user_data['first_name']
        self.last_name = user_data['last_name']
        self.email = user_data['email']
        self.password = self.hash_password(user_data['password'])


class Poke(db.Model):
    poke_name = db.Column(db.String, primary_key=True)
    img_url = db.Column(db.String, nullable=False)
    ability = db.Column(db.String, nullable=False)
    hp = db.Column(db.Integer, nullable=False)
    attack = db.Column(db.Integer, nullable=False)
    defense = db.Column(db.Integer, nullable=False)
    # FK
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))


    # This method will assign our columns with their respective values
    def from_dict(self, poke_data):
        print('poke data here')
        print(poke_data) 
        self.poke_name = poke_data['poke_name']
        self.img_url = poke_data['img_url']
        self.ability = poke_data['ability']
        self.hp = poke_data['hp']
        self.attack = poke_data['attack']
        self.defense = poke_data['defense']
        self.user_id = int(poke_data['user_id'])

# only need the model


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

app/blueprints/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, HiddenField, IntegerField
from wtforms.validators import DataRequired

class PokemonForm(FlaskForm):
    pokemon = StringField('Pokemon', validators=[DataRequired()])
    submit = SubmitField('Submit')
    poke_name = HiddenField('poke_name', validators=[DataRequired()])
    img_url = HiddenField('Image URL', validators=[DataRequired()])
    ability = HiddenField('Ability', validators=[DataRequired()])
    hp = HiddenField('HP', validators=[DataRequired()])
    attack = HiddenField('Attack', validators=[DataRequired()])
    defense = HiddenField('Defense', validators=[DataRequired()])

class CapturePokemon(FlaskForm):
    poke_name = HiddenField('Pokemon Name', validators=[DataRequired()])
    img_url = HiddenField('Image URL', validators=[DataRequired()])
    ability = HiddenField('Ability', validators=[DataRequired()])
    hp = HiddenField('HP', validators=[DataRequired()])
    attack = HiddenField('Attack', validators=[DataRequired()])
    defense = HiddenField('Defense', validators=[DataRequired()])
    user_id = IntegerField('User ID')

app/__init__.py
from flask import Flask
from config import Config
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

login_manager = LoginManager()
db = SQLAlchemy()
migrate = Migrate()

def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)

    # Register packages
    login_manager.init_app(app)
    db.init_app(app)
    migrate.init_app(app, db)

    #login_manager settings
    login_manager.login_view = 'auth.login'
    login_manager.login_message = 'You must be logged in to view this page!'
    login_manager.login_message_category = 'warning'

    # Import Blueprints
    from app.blueprints.main import main
    from app.blueprints.auth import auth
    from app.blueprints.poke import poke

    # Register Blueprints
    app.register_blueprint(main)
    app.register_blueprint(auth)
    app.register_blueprint(poke)

    return app

app/blueprints/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import routes

app/blueprints/main/routes.py
from flask import request, flash, jsonify, render_template, redirect, url_for
import requests
from app import db
from app.blueprints.main.forms import PokemonForm, CapturePokemon
from app.models import Poke, User
from flask_login import login_required, current_user
from . import main


@main.route("/")
@main.route('/home')
def home():
    return render_template('home.html')

@main.route('/pokemon_search', methods=['GET', 'POST'])
@login_required
def pokemon_search():
    form = PokemonForm()
    if request.method == 'POST':
        pokemon = request.form.get('pokemon')

        def getPokemonInfo():
            base_url = 'https://pokeapi.co/'
            url = f'{base_url}api/v2/pokemon/{pokemon}'
            response = requests.get(url)

            if response.ok:
                data = response.json()
                front_shiny = data['sprites']['front_shiny']
                ability = data['abilities'][0]['ability']['name']
                hp_stat = data['stats'][0]['base_stat']
                attack_stat = data['stats'][1]['base_stat']
                defense_stat = data['stats'][2]['base_stat']

                return {
                    'name': pokemon,
                    'front_shiny': front_shiny,
                    'ability': ability,
                    'hp_stat': hp_stat,
                    'attack_stat': attack_stat,
                    'defense_stat': defense_stat
                }

        pokemon_info = getPokemonInfo()

        # Populate the hidden fields in the form
        form.poke_name.data = pokemon_info['name']
        form.img_url.data = pokemon_info['front_shiny']
        form.ability.data = pokemon_info['ability']
        form.hp.data = pokemon_info['hp_stat']
        form.attack.data = pokemon_info['attack_stat']
        form.defense.data = pokemon_info['defense_stat']
        
        

        return render_template('pokemon_search.html', form=form, pokemon_info=pokemon_info)

    return render_template('pokemon_search.html', form=form)


@main.route('/add_pokemon', methods=['POST'])
@login_required
def add_pokemon():
    print("add_pokemon function is being called")
    form = CapturePokemon(request.form)
    if request.method == 'POST' and form.validate_on_submit():

        existing_pokemon_count = Poke.query.filter_by(user_id=current_user.id).count()
        if existing_pokemon_count >= 5:
            flash('You have reached the maximum limit of stored Pokémon. Click here to edit your team', 'danger')
            return redirect(url_for('main.pokemon_search'))
        
        print(form.data)

        pokemon_data = {
            'poke_name': form.poke_name.data,
            'img_url': form.img_url.data,
            'ability': form.ability.data,
            'hp': form.hp.data,
            'attack': form.attack.data,
            'defense': form.defense.data,
            'user_id': current_user.id
        }

        new_pokemon = Poke()

        new_pokemon.from_dict(pokemon_data)

        db.session.add(new_pokemon)
        db.session.commit()

        flash('Pokemon added successfully!', 'success')
    else:
        flash('Invalid form data', 'danger')
        print('Error Here:')
        print(form.errors)
        print(f"Current User ID: {current_user.id}")
          # Print form validation errors

    # Redirect to the 'pokemon_search' endpoint
    return redirect(url_for('main.pokemon_search'))

@main.route('/pokemon_team')
@login_required
def pokemon_team():
    user = User.query.get(current_user.id)
    team = user.poke  # Assuming the user's Pokémon team is stored in a field called 'pokemon_team'
    return render_template('pokemon_team.html', team=team)

@main.route('/pokemon_team/delete/<poke_name>', methods=['POST', 'DELETE'])
@login_required
def delete_pokemon(poke_name):
    pokemon = Poke.query.filter_by(poke_name=poke_name, user_id=current_user.id).first()
    if pokemon:
        db.session.delete(pokemon)
        db.session.commit()
        flash('Pokemon deleted successfully!', 'success')
    else:
        flash('Pokemon not found or you do not have permission to delete it.', 'danger')

    return redirect(url_for('main.pokemon_team'))

app/blueprints/poke/__init__.py
from flask import Blueprint

poke = Blueprint('poke', __name__, template_folder='poke_templates', url_prefix='/poke')

from . import routes

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300&family=Rajdhani&family=Russo+One&display=swap" rel="stylesheet">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css')}}">
    <link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('static', filename='images/apple-touch-icon.png')}}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='images/favicon-32x32.png')}}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='images/favicon-16x16.png')}}">
    <link rel="manifest" href="{{ url_for('static', filename='images/site.webmanifest')}}">
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    {% if current_user.is_authenticated %}
                        <a class="nav-link active me-4" aria-current="page" href="{{ url_for('main.home') }}">Home</a>
                        <a class="nav-link me-4" href="{{ url_for('main.pokemon_search') }}">Search For Pokemon</a>
                        <a class="nav-link me-4">Hello, {{ current_user.first_name }}</a>
                        <a class="nav-link me-4" href="{{ url_for('main.pokemon_team') }}">Pokemon Team</a>
                        <a class="btn btn-secondary ms-4" href="{{ url_for('auth.logout') }}">Logout</a>
                    {% else %}
                        <a class="nav-link me-4" href="{{ url_for('auth.login') }}">Log In</a>
                        <a class="nav-link me-4" href="{{ url_for('auth.signup') }}">Sign Up</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
            <div class="alert alert-{{category}} alert-dismissible fade show" role="alert">
                <p class="m-0">{{ message }}</p>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
              </div>
              {% endfor %}
        {% endif %}
    {% endwith %}
    {% block content %}

    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</body>
</html>

app/templates/home.html
{% extends 'base.html' %}

{% block title %}
    Home Page
{% endblock %}

{% block content %}
    <div class="mt-4 home_content ">
        <div class="text-center">
            <h1>Welcome to my Pokemon app!</h1>
            <p>Click the cute little pikachu below to begin your Pokemon adventure!</p>
        </div>
        <a href="{{ url_for('main.pokemon_search') }}">
            <img src="{{ url_for('static', filename='images/Pikachu.jpg') }}" 
            alt="Pikachu" class="d-block mx-auto img-fluid" style="max-width: 200px;">
        </a> 
    </div>
{% endblock %}

app/templates/login.html
{% extends 'base.html' %}

{% block title %}
    Log In Page
{% endblock %}

{% block content %}
<h1 class ='text-center'>Pokemon Login Page</h1>
<div class="container w-25" id="form-container">
    <form method="POST" class="px-3">
        {{ form.csrf_token }}
        <div class="mb-3">
            {{ form.email.label(class="form-label") }}
            {{ form.email(class="form-control") }}
        </div>
        <div class="mb-3">
            {{ form.password.label(class="form-label") }}
            {{ form.password(class="form-control") }}
        </div>
        {{ form.submit(class="btn btn-primary d-block mx-auto") }}
    </form>
    {% if error %}
        <p class="text-center mt-3 text-danger">{{ error }}</p>
    {% endif %}
</div>

{% endblock %}

app/templates/pokemon_search.html
{% extends 'base.html' %}

{% block title %}
    Pokemon Search
{% endblock %}

{% block content %}
    <div class="mt-3">
        <form method="POST" class="px-3">
            {{ form.hidden_tag() }} 
            {{ form.pokemon }}
            {{ form.submit }}
            {{ form.poke_name }}
            {{ form.img_url }}
            {{ form.ability }}
            {{ form.hp }}
            {{ form.attack }}
            {{ form.defense }}
        </form>
    </div>

    {% if pokemon_info %}
        <div class="container">
            <div class="d-flex justify-content-center">
                <div class="card">
                    <h2 class="card-title text-center">{{ pokemon_info.name }}</h2>
                    <img src="{{ pokemon_info.front_shiny }}" alt="Pokemon Image" class="card-img-top img-fluid pokemon-image"> 
                    <div class="card-body">
                        <p class="card-text">Ability: {{ pokemon_info.ability }}</p>
                        <p class="card-text">HP Stat: {{ pokemon_info.hp_stat }}</p>
                        <p class="card-text">Attack Stat: {{ pokemon_info.attack_stat }}</p>
                        <p class="card-text">Defense Stat: {{ pokemon_info.defense_stat }}</p>
                    </div>
                    <div class="card-footer text-center">
                        <form method="POST" action="{{ url_for('main.add_pokemon') }}">
                            {{ form.hidden_tag() }}  
                            {{ form.poke_name }}
                            {{ form.img_url }}
                            {{ form.ability }}
                            {{ form.hp }}
                            {{ form.attack }}
                            {{ form.defense }}
                            {{ form.user_id }}
                            <button type="submit" class="btn btn-custom">
                                <img src="{{ url_for('static', filename='images/pokeball.png') }}" alt="Pokeball" class="pokeball-image">
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

app/templates/pokemon_team.html
<!-- pokemon_team.html -->

{% extends 'base.html' %}

{% block content %}
  <h1>Your Pokémon Team</h1>

  <div class="row">
    {% for pokemon in team %}
      <div class="col-md-4">
        <div class="card mb-3">
          <img src="{{ pokemon.img_url }}" class="card-img-top" alt="{{ pokemon.poke_name }}">
          <div class="card-body">
            <h5 class="card-title">{{ pokemon.poke_name }}</h5>
            <ul class="list-group list-group-flush">
              <li class="list-group-item">Ability: {{ pokemon.ability }}</li>
              <li class="list-group-item">HP: {{ pokemon.hp }}</li>
              <li class="list-group-item">Attack: {{ pokemon.attack }}</li>
              <li class="list-group-item">Defense: {{ pokemon.defense }}</li>
            </ul>
          </div>
          <div class="card-footer">
            <form action="{{ url_for('main.delete_pokemon', poke_name=pokemon.poke_name) }}" method="POST">
              <input type="hidden" name="_method" value="DELETE">
              <button type="submit" class="btn btn-danger">Delete</button>
            </form>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock %}

app/templates/signup.html
{% extends 'base.html' %}

{% block title %}
    Signup Page
{% endblock %}

{% block content %}
<div class="container w-25" id="form-container">
    <form method="POST" class="px-3">
        {{ form.csrf_token }}
        <div class="mb-3">
            {{ form.first_name.label(class="form-label") }}
            {{ form.first_name(class="form-control") }}
        </div>
        <div class="mb-3">
            {{ form.last_name.label(class="form-label") }}
            {{ form.last_name(class="form-control") }}
        </div>
        <div class="mb-3">
            {{ form.email.label(class="form-label") }}
            {{ form.email(class="form-control") }}
        </div>
        <div class="mb-3">
            {{ form.password.label(class="form-label") }}
            {{ form.password(class="form-control") }}
        </div>
        <div class="mb-3">
            {{ form.confirm_password.label(class="form-label") }}
            {{ form.confirm_password(class="form-control") }}
        </div>
        {{ form.submit(class="btn btn-primary d-block mx-auto") }}
    </form>
</div>

{% endblock %}